export default {
  layout: 'dashboard',
  auth: false,
  props: {
    patient_info: {
      type: Object,
      default() {
        return {
          name: 'Neil Humprey O. Laquihon',
          use: 'Internal Medicine',
          clinic: 'Laquihon Medical Clinic',
          number: 'Tell #288-500',
          date: '01/21/21',
          time: '21:05 Am',
        }
      },
    },
  },
  data() {
    return {
      amount: '1',
      take: '2',
      items: ['1', '2', '3', '4'],
      minimumAM: 0,
      minimumPM: 0,
      duration: '31',
      durations: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
      ],
      hoursLabelAM: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
      ],
      hoursLabelPM: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
      ],
    }
  },
}
