export default {
  layout: 'dashboard',
  auth: false,
  methods: {
    prescription() {
      this.$store.dispatch('snackbar/setSnackbar', {
        text: `You have successfully created the prescrition`,
      })
      this.$router.push('/doctors')
    },
    cancel() {},
  },
  data() {
    return {
      patient_prescription_name: '',
      patient_prescription_age: '',
      patient_prescription_sex: '',
      patient_prescription_number: '',
      patient_prescription_address: '',
      medicine_prescription_name: '',
      medicine_prescription_dosage: '',
      medicine_prescription_brand: '',
      patient_prescription_note: '',
      patient_info: {
        image: 'medical-pharmacy-logo.jpg',
        name: 'Mel Ligoro',
        time: '12:30 PM',
        number: '09189789876',
        use: 'Skin',
        clinic: 'Pharmacy',
        message:
          'Cookie jelly cake lemon drops cotton candy lemon drops cake. Sweet roll chocolate pudding. Sweet dessert cheesecake topping cotton candy ice cream chocolate cake gummies.',
      },
      med_type: false,
      med_method: false,
      amount: '1',
      take: '2',
      items: ['1', '2', '3', '4'],
      minimumAM: 0,
      minimumPM: 0,
      duration: '31',
      durations: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
      ],
      hoursLabelAM: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
      ],
      hoursLabelPM: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
      ],
    }
  },
}
